### ISSUE TITLE
when i installed both xwsl and kali-xrdp are not working together

### ISSUE THREAD

**Issue by Vikaash301** [DesktopECHO/Kali-xRDP#2] opened 2021-10-01 11:42 UTC

**Comment by Vikaash301** [comment] 2021-10-01 11:54
when i want  to use kali-xrdp i need to restart the wsl  kali and shut down xwsl  using powershell to use remote desktop 
.Please update the script to be more like xWSL .It is more easy and user friendly to use  . Mainly i cannot use kali and xwsl even though  i have 2 gig dedicated to graphics  the response is slow  . I cannot use both simultaneously .Please use the network as briged like a vm as replicate the phisical state and allow simultaneously use of both ubuntu and kali together and increses the graphics ram and allow 3d acceleration so it even beat vmware . That would be awesome . then it will be more user friendly for a normal windows pc user .

**Comment by Vikaash301** [comment] 2021-10-01 11:55
Could you do a hacingtosh  using  wsl2 costom kernal using macos .deb file

**Comment by Vikaash301** [comment] 2021-10-01 11:59
use macos itself as a distribution insted of using linux distribution to install macos using qmu .
i tried it but it failed and takes so much time
and terminate the wsl instance as soon as the remote desktop is closed it saves a lot of resources

**Comment by Vikaash301** [comment] 2021-10-01 11:59
thank you!

**Comment by Vikaash301** [comment] 2021-10-01 12:00
i wish you could do it
thank you very much
it helps many developers and freelancers

**Comment by DesktopECHO** [comment] 2021-10-01 17:53
Hi, I can't reproduce your issue.
Sorry, the other things you mentioned are way out of scope for this project.  Closing.    

![image](https://user-images.githubusercontent.com/33142753/135665138-a558c5a7-7dc3-4265-a1ee-2114adee5f8d.png)

**Closed by DesktopECHO** 2021-10-01 17:53 UTC
